CREATE TABLE TV_SHOW (
  ID          VARCHAR(36)  NOT NULL,
  NAME        VARCHAR(255) NOT NULL,
  URL         VARCHAR(255) NOT NULL,
  IMAGE       VARCHAR(255),
  RATING      FLOAT,
  PRIMARY KEY (ID)
);

CREATE TABLE APPUSER (
  ID          VARCHAR(36)   NOT NULL,
  FIRST_NAME  VARCHAR(255)  NOT NULL,
  LAST_NAME   VARCHAR(255)  NOT NULL,
  EMAIL       VARCHAR(255)  UNIQUE NOT NULL,
  PRIMARY KEY (ID)
)